sudo: required
services:
  - docker

before_install:
  - docker build -t unchartedzone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true unchartedzone/docker-react npm run test

language: generic

deploy: 
  provider: elasticbeanstalk
  region:  "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-142354486278"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
